### ISSUE TITLE
README regarding Working with API Integration

### ISSUE THREAD

**Issue by rmchapa** [CrowdStrike/foundry-js#65]
foundry-js/README.md lines 117-119 state that you only need operationId to call an API, however you also need the definitionId.  If you leave the definition ID out, it attempts to use the app-id as the definitionId causing a 404.

It should be changed from:
```
  const apiIntegration = falcon.apiIntegration({
    operationId: 'Get Cities',
  });
```

to this:
```
  const apiIntegration = falcon.apiIntegration({
    definitionId: 'abcdef1234567890abcdef1234567890',
    operationId: 'Get Cities',
  });
```

**Comment by mraible** [comment]
@rlucha-crowdstrike Can you please confirm this is an issue?

**Comment by rlucha-crowdstrike** [comment]
Looking into this.

**Comment by mraible** [comment]
@rmchapa I was able to reproduce this problem and you're right: adding a `definitionId` that matches what's in `manifest.yml` fixes this.

**Comment by rlucha-crowdstrike** [comment]
@mraible were you able to reproduce it with a simple application?

**Comment by mraible** [comment]
Yes
